/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ["./src/**/*.{js,ts,jsx,tsx}"],
  theme: {
    extend: {
      colors: {
        background: "var(--background)",
        foreground: "var(--foreground)",

        card: "var(--card)",
        "card-foreground": "var(--card-foreground)",

        popover: "var(--popover)",
        "popover-foreground": "var(--popover-foreground)",

        primary: "var(--primary)",
        footer: "var(--footer)",
        "primary-foreground": "var(--primary-foreground)",

        secondary: "var(--secondary)",
        "secondary-foreground": "var(--secondary-foreground)",

        muted: "var(--muted)",
        "muted-foreground": "var(--muted-foreground)",

        accent: "var(--accent)",
        "accent-foreground": "var(--accent-foreground)",

        destructive: "var(--destructive)",
        "destructive-foreground": "var(--destructive-foreground)",

        border: "var(--border)",
        input: "var(--input)",
        ring: "var(--ring)",

        "chart-1": "var(--chart-1)",
        "chart-2": "var(--chart-2)",
        "chart-3": "var(--chart-3)",
        "chart-4": "var(--chart-4)",
        "chart-5": "var(--chart-5)",

        sidebar: "var(--sidebar)",
        "sidebar-foreground": "var(--sidebar-foreground)",
        "sidebar-primary": "var(--sidebar-primary)",
        "sidebar-primary-foreground": "var(--sidebar-primary-foreground)",
        "sidebar-accent": "var(--sidebar-accent)",
        "sidebar-accent-foreground": "var(--sidebar-accent-foreground)",
        "sidebar-border": "var(--sidebar-border)",
        "sidebar-ring": "var(--sidebar-ring)",
        "portal-brand": "var(--portal-brand)",
        "portal-brand-strong": "var(--portal-brand-strong)",
        "portal-brand-soft": "var(--portal-brand-soft)",
        "portal-gold": "var(--portal-gold)",
        "portal-gold-strong": "var(--portal-gold-strong)",
        "portal-surface": "var(--portal-surface)",
        "portal-surface-soft": "var(--portal-surface-soft)",
        "portal-surface-muted": "var(--portal-surface-muted)",
        "portal-surface-gold": "var(--portal-surface-gold)",
        "portal-border": "var(--portal-border)",
        "portal-border-soft": "var(--portal-border-soft)",
        "portal-border-strong": "var(--portal-border-strong)",
        "portal-border-muted": "var(--portal-border-muted)",
        "portal-text": "var(--portal-text)",
        "portal-text-strong": "var(--portal-text-strong)",
        "portal-text-body": "var(--portal-text-body)",
        "portal-text-muted": "var(--portal-text-muted)",
        "portal-text-soft": "var(--portal-text-soft)",
        "portal-status-success-bg": "var(--portal-status-success-bg)",
        "portal-status-success-text": "var(--portal-status-success-text)",
        "portal-status-danger-bg": "var(--portal-status-danger-bg)",
        "portal-status-danger-text": "var(--portal-status-danger-text)",
        "portal-status-info-bg": "var(--portal-status-info-bg)",
        "portal-status-info-text": "var(--portal-status-info-text)",
        "portal-status-warning-bg": "var(--portal-status-warning-bg)",
        "portal-status-warning-text": "var(--portal-status-warning-text)",
        "shared-eyebrow": "var(--shared-eyebrow)",
        "shared-title": "var(--shared-title)",
        "shared-description": "var(--shared-description)",
        "shared-label": "var(--shared-label)",
        "shared-value": "var(--shared-value)",
        "shared-heading": "var(--shared-heading)",
        "shared-table-head": "var(--shared-table-head)",
        "shared-helper-bg": "var(--shared-helper-bg)",
        "shared-helper-text": "var(--shared-helper-text)",
        "topbar-border": "var(--topbar-border)",
        "topbar-accent": "var(--topbar-accent)",
        "topbar-link": "var(--topbar-link)",
        "topbar-button-text": "var(--topbar-button-text)",
        "topbar-input-text": "var(--topbar-input-text)",
        "topbar-placeholder": "var(--topbar-placeholder)",
        "admin-field-label": "var(--admin-field-label)",
        "admin-field-border": "var(--admin-field-border)",
        "admin-field-bg": "var(--admin-field-bg)",
        "admin-field-text": "var(--admin-field-text)",
        "admin-field-focus-border": "var(--admin-field-focus-border)",
        "admin-field-focus-ring": "var(--admin-field-focus-ring)",
        "admin-field-disabled-bg": "var(--admin-field-disabled-bg)",
        "admin-field-disabled-text": "var(--admin-field-disabled-text)",
        "admin-tab-bg": "var(--admin-tab-bg)",
        "admin-tab-active-text": "var(--admin-tab-active-text)",
        "admin-tab-inactive-text": "var(--admin-tab-inactive-text)",
        "admin-error-border": "var(--admin-error-border)",
        "admin-error-bg": "var(--admin-error-bg)",
        "admin-error-text": "var(--admin-error-text)",
        "admin-registry-border": "var(--admin-registry-border)",
        "admin-registry-border-alt": "var(--admin-registry-border-alt)",
        "admin-registry-bg": "var(--admin-registry-bg)",
        "admin-registry-chip-bg": "var(--admin-registry-chip-bg)",
        "admin-registry-chip-text": "var(--admin-registry-chip-text)",
        "admin-registry-count": "var(--admin-registry-count)",
        "admin-registry-title": "var(--admin-registry-title)",
        "admin-registry-text": "var(--admin-registry-text)",
        "admin-registry-strong": "var(--admin-registry-strong)",
        "staff-frame-red-border": "var(--staff-frame-red-border)",
        "staff-frame-gold-border": "var(--staff-frame-gold-border)",
        "staff-frame-base": "var(--staff-frame-base)",
        "staff-frame-red-end": "var(--staff-frame-red-end)",
        "staff-frame-gold-end": "var(--staff-frame-gold-end)",
        "staff-payload-border": "var(--staff-payload-border)",
        "staff-payload-text": "var(--staff-payload-text)",
        "staff-payload-heading": "var(--staff-payload-heading)",
        "staff-payload-code": "var(--staff-payload-code)",
        "staff-list-border": "var(--staff-list-border)",
        "staff-list-label": "var(--staff-list-label)",
        "staff-empty-border": "var(--staff-empty-border)",
        "staff-empty-text": "var(--staff-empty-text)",
        "staff-selected-border": "var(--staff-selected-border)",
        "staff-selected-bg": "var(--staff-selected-bg)",
        "staff-hover-border": "var(--staff-hover-border)",
        "staff-name": "var(--staff-name)",
        "staff-meta": "var(--staff-meta)",
        "staff-meta-soft": "var(--staff-meta-soft)",
        "staff-selected-icon": "var(--staff-selected-icon)",
        "staff-detail-border": "var(--staff-detail-border)",
        "analytics-series-primary": "var(--analytics-series-primary)",
        "analytics-series-secondary": "var(--analytics-series-secondary)",
        "analytics-chart-bg": "var(--analytics-chart-bg)",
        "analytics-chart-bar-bg": "var(--analytics-chart-bar-bg)",
        "analytics-revenue-card": "var(--analytics-revenue-card)",
        "analytics-gold-label": "var(--analytics-gold-label)",
        "analytics-gold-value": "var(--analytics-gold-value)",
        "portal-text-faded": "var(--portal-text-faded)",
        "student-title": "var(--student-title)",
        "student-value": "var(--student-value)",
        "portal-gold-chip-bg": "var(--portal-gold-chip-bg)",
        "portal-gold-chip-text": "var(--portal-gold-chip-text)",
        "portal-status-success-soft-bg": "var(--portal-status-success-soft-bg)",
        "portal-status-success-soft-text": "var(--portal-status-success-soft-text)",
        "portal-surface-warm": "var(--portal-surface-warm)",
        "portal-panel": "var(--portal-panel)",
        "admin-audit-card": "var(--admin-audit-card)",
      },
      fontFamily: {
        sans: ["Inter", "system-ui", "sans-serif"],
        serif: ["Playfair Display", "Georgia", "serif"],
      },
      borderRadius: {
        lg: "var(--radius)",
        md: "calc(var(--radius) - 2px)",
        sm: "calc(var(--radius) - 4px)",
      },
    },
  },
  plugins: [],
};
